# Generated by Django 2.2.17 on 2020-12-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0002_auto_20201231_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
