# Generated by Django 2.2.17 on 2021-01-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0003_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(default='https://www.gravatar.com/avatar/0?s=90&d=identicon&r=PG'),
        ),
    ]
