# Generated by Django 2.2.17 on 2021-01-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0005_auto_20210105_1145'),
        ('stackoverflow', '0007_auto_20210105_1633'),
    ]

    operations = [
    ]
