# Generated by Django 2.2.17 on 2021-01-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0008_merge_20210106_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
