# Generated by Django 2.2.17 on 2021-01-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0008_merge_20210106_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')], default=1),
        ),
    ]
