# Generated by Django 2.2.17 on 2021-01-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0009_auto_20210106_1913'),
        ('stackoverflow', '0011_auto_20210107_0547'),
    ]

    operations = [
    ]
