# Generated by Django 2.2.17 on 2021-01-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0012_merge_20210107_0615'),
        ('stackoverflow', '0012_merge_20210107_0556'),
    ]

    operations = [
    ]
